name: Auto Merge Surge Rules

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  merge-job:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 下载私有 merge.py
        run: |
          curl \
          -H "Authorization: token ${{ secrets.PRIVATE_REPO_TOKEN }}" \
          -L \
          https://raw.githubusercontent.com/MrPan109/LSS-IN/refs/heads/master/Auto/merge.py \
          -o merge.py

      - name: 执行合并脚本
        run: python merge.py

      - name: 提交更新
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add AutoRule/AdDIY.list

          if ! git diff --cached --quiet; then
            git commit -m "chore: 自动更新规则"
            git push
          else
            echo "规则没有变化"
          fi
